# Default values for webapp.
# This is a YAML-formatted file.

image:
  # -- Image registry and repo
  repository: docker.io/nginx
  # -- Pull policy
  pullPolicy: IfNotPresent
  # -- Tag of image to use
  tag: latest

# -- Number of pod replicas
replicaCount: 1

# -- Environmental vars, key value pairs, e.g. `MY_VAR: 'value 123'`
env: {}
#  MY_VAR: 'value 123'

# -- Env vars from Secrets, the key is env var name, `secretName` and `secretKey` reference the Secret
secretEnv: {}
#  SECRET_THING:
#    secretName: my-secret
#    secretKey: password

# Network traffic to the pods
service:
  # -- Service type, change to LoadBalancer or NodePort to expose traffic outside the cluster
  type: ClusterIP
  # -- Port the service accepts traffic on
  port: 80
  # -- Port the container accepts traffic on
  targetPort: 8080
  # -- Service annotations
  annotations: {}

# Configure Ingress, switch on/off-able
ingress:
  # -- Use an ingress or not
  enabled: false
  # -- Set the IngressClass to use
  className:
  # -- Ingress host *must* be set if enabled
  host:
  tls:
    # -- Use TLS on ingress
    enabled: false
    # -- Secret holding cert *must* be set if TLS enabled
    secretName:
  # -- Extra annotations to set on the ingress
  annotations: {}

# Limit resources
resources:
  limits:
    # -- CPU hard limit
    cpu: 1000m
    # -- Memory hard limit
    memory: 256Mi
  requests:
    # -- CPU resource request
    cpu: 200m
    # -- Memory resource request
    memory: 128Mi

# -- Any secrets needed to pull image
imagePullSecrets: []
# -- Override the chart name used for this release
nameOverride: ""
# -- Override full release name, normally autogenerated
fullnameOverride: ""

livenessProbe:
  # -- URL path checked by liveness & readiness probes
  path: /
  # -- Number of liveness probe failures to tolerate
  failureThreshold: 3
  # -- Delay before liveness probe starts
  initialDelaySeconds: 20
  # -- Interval between liveness probe checks
  periodSeconds: 20

serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- The name of the service account to use. If not set a name is generated
  name:

persistence:
  # -- Use persistent volume
  enabled: false
  # -- Persistent volume size
  size: 1Gi
  # -- Persistent volume access mode
  accessMode: ReadWriteOnce
  # -- Persistent volume mount path, must be set if enabled
  mountPath:

# -- Pod security context spec
podSecurityContext: {}

# -- Security context spec
securityContext: {}

# -- Node selector spec
nodeSelector: {}

# -- Node tolerations spec
tolerations: []

# -- Node affinity spec
affinity: {}

# -- Pod annotations
podAnnotations: {}

# -- Pod labels
podLabels: {}

# -- Deployment annotations
deploymentAnnotations: {}

# -- PVC annotations
pvcAnnotations: {}
